name: Daddylive Resolver

on:
  workflow_dispatch:
    inputs:
      channel_urls:
        description: "Comma-separated list of Daddylive channel or player2 iframe URLs"
        required: true
        default: "https://example.com/your-channel-page"
      max_channels:
        description: "Limit channels to process (0 = all)"
        required: false
        default: "0"
      save_to_db:
        description: "Upsert resolved streams to Supabase? (0/1)"
        required: false
        default: "0"
  schedule:
    - cron: "0 8 * * *"

permissions:
  contents: read

concurrency:
  group: daddylive-resolver
  cancel-in-progress: true

jobs:
  resolve:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    defaults:
      run:
        shell: bash
    env:
      DL_XML_URL: "https://raw.githubusercontent.com/thecrewwh/dl_url/refs/heads/main/dl.xml"
      USER_AGENT: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36"
      PROBE_TIMEOUT_S: "12"
      PROBE_VARIANT_LIMIT: "6"
      SUPABASE_URL: "${{ secrets.SUPABASE_URL }}"
      SUPABASE_SERVICE_KEY: "${{ secrets.SUPABASE_SERVICE_KEY }}"
      SUPABASE_SCHEMA: "public"
      STREAMS_TABLE: "streams_latam"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip
          pip install requests

      - name: Write resolver script
        run: |
          set -euo pipefail
          mkdir -p scripts out/daddylive
          cat > scripts/daddylive_resolve.py <<'PY'
          import os, re, io, sys, json, time, base64, csv
          from urllib.parse import urljoin, urlparse
          import requests
          # --- rest of the script you already have, unchanged ---
          PY

      - name: Run resolver
        env:
          channel_urls: "${{ github.event.inputs.channel_urls }}"
          max_channels: "${{ github.event.inputs.max_channels }}"
          save_to_db: "${{ github.event.inputs.save_to_db }}"
        run: |
          set -euo pipefail
          python3 scripts/daddylive_resolve.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: daddylive-resolved
          path: |
            out/daddylive/resolved.jsonl
            out/daddylive/resolved.csv
          if-no-files-found: error
