name: Deploy xmltv Edge Function

on:
  push:
    paths:
      - "supabase/functions/xmltv/**"
      - ".github/workflows/deploy-xmltv.yml"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      # Optional: only if you want to set/override secrets from CI instead of the dashboard.
      # Make sure SUPABASE_SERVICE_ROLE_KEY is in GitHub Secrets if you enable this step.
      # - name: Ensure function secrets exist
      #   run: |
      #     supabase secrets set \
      #       SUPABASE_URL="https://${SUPABASE_PROJECT_REF}.supabase.co" \
      #       SUPABASE_SERVICE_ROLE_KEY="${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
      #       --project-ref "${SUPABASE_PROJECT_REF}"

      - name: Deploy xmltv
        run: |
          supabase functions deploy xmltv \
            --project-ref "${SUPABASE_PROJECT_REF}" \
            --no-verify-jwt
