name: EPG-MX

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 7 * * *" # daily 07:00 UTC

concurrency:
  group: epg-mx
  cancel-in-progress: true

jobs:
  mx:
    runs-on: ubuntu-latest
    timeout-minutes: 300

    env:
      MX_SEARCH_URL: "https://iptv-org.github.io/?q=live%20country:MX"
      # GatoTV directory root (no XMLTV fallback in this test)
      GATOTV_DIR_URL: "https://www.gatotv.com/canales_de_tv"
      GATOTV_SCORE_MIN: "0.80"        # matcher threshold (Jaccard+brand bonus)
      GATOTV_TZ: "America/Mexico_City" # default tz for schedule times
      PROGRAMS_HOURS_AHEAD: "24"      # strictly 24h window
      HEADLESS: "true"
      MAX_CHANNELS: "0"
      PER_PAGE_DELAY_MS: "150"
      NAV_TIMEOUT_MS: "30000"
      PROBE_TIMEOUT_MS: "5000"

      # DB
      SUPABASE_SCHEMA: "public"
      SUPABASE_TABLE: "mx_channels"    # streams table (unchanged)
      PROGRAMS_TABLE: "epg_programs"   # programs table
      SUPABASE_URL: "${{ secrets.SUPABASE_URL }}"
      SUPABASE_SERVICE_KEY: "${{ secrets.SUPABASE_SERVICE_KEY }}"

      # VPN (optional)
      NORDVPN_TOKEN: "${{ secrets.NORDVPN_TOKEN }}"

      # Optional manual URL map JSON
      GATOTV_MAPPING_URL: "${{ secrets.GATOTV_MAPPING_URL }}"
