name: Build & Push EPG to Supabase

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *" # every 6 hours

env:
  COUNTRIES: "US,PR,MX,CA,IT,ES,GB,AU,IE,DE,DO"  # NOTE: UK => GB in ISO-2
  DAYS: "2"
  MAX_CONNECTIONS: "6"
  TABLE: "epg_programs"

jobs:
  epg:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Check out your repo
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install script deps
        run: npm install

      - name: Clone iptv-org/epg
        run: |
          git clone --depth 1 https://github.com/iptv-org/epg.git epg
          cd epg
          npm ci

      - name: Build channels.xml for selected countries
        run: node scripts/make-channels-xml.mjs "$COUNTRIES"

      - name: Grab EPG (this creates guide.xml)
        working-directory: epg
        run: |
          mkdir -p ../build
          npm run grab --- \
            --channels=../build/channels.xml \
            --output ../build/guide.xml \
            --days="${{ env.DAYS }}" \
            --maxConnections="${{ env.MAX_CONNECTIONS }}"

      - name: Upload guide.xml as artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: guide.xml
          path: build/guide.xml

      - name: Push to Supabase
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          SUPABASE_TABLE: ${{ env.TABLE }}
        run: node scripts/push-to-supabase.mjs build/guide.xml build/channels.xml
