name: EPG (manual)

on:
  workflow_dispatch:
    inputs:
      countries:
        description: "Comma-separated ISO codes (US,PR,MX,CA,IT,ES,GB,AU,IE,DE,DO)"
        required: false
        default: "US,PR,MX,CA,IT,ES,GB,AU,IE,DE,DO"

jobs:
  sanity:
    runs-on: ubuntu-latest
    steps:
      - name: Show inputs
        run: |
          echo "Triggered on: $GITHUB_REF"
          echo "countries='${{ github.event.inputs.countries }}'"
