name: Open-EPG ingest (self-hosted Pi)

on:
  workflow_dispatch:
    inputs:
      window_hours:
        description: "Hours window (0 = off)"
        type: number
        default: 0
      debug_dump_count:
        description: "How many programme children to dump"
        type: number
        default: 10
      save_xml:
        description: "Upload fetched XML as artifact"
        type: boolean
        default: true

jobs:
  ingest:
    # ✅ Use the labels your Pi runner actually has, or just "self-hosted"
    runs-on: [self-hosted]  # or [self-hosted, Linux, ARM64, pi, home, hiptv.ddns.net]
    timeout-minutes: 60

    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
      OPEN_EPG_FILES: "https://www.open-epg.com/files/puertorico1.xml,https://www.open-epg.com/files/puertorico2.xml"
      WINDOW_HOURS: ${{ github.event.inputs.window_hours }}
      ENFORCE_LIVE: "0"
      PREFER_LANGS: "es-pr,es,en"
      DEBUG_DUMP_PROGRAM_CHILDREN: ${{ github.event.inputs.debug_dump_count }}
      SAVE_XML: ${{ github.event.inputs.save_xml }}
      REFRESH_MV: "1"
      REFRESH_MV_FUNC: "refresh_programs_next_12h"
      TEST_LOOKUP_CHANNEL: "3ABN LATINO WTPM DT3 PUERTO RICO.pr"
      TEST_LOOKUP_START: "20250822223000 +0000"

    steps:
      - uses: actions/checkout@v4

      # Optional: ensure python3/venv/pip exist (most Pi Bookworm images already have them)
      - name: Ensure system Python is present
        run: |
          set -e
          if ! command -v python3 >/dev/null; then
            sudo apt-get update
            sudo apt-get install -y python3 python3-venv python3-pip
          fi
          python3 -V

      - name: Create venv & install deps
        run: |
          set -e
          python3 -m venv .venv
          . .venv/bin/activate
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: Run ingest
        run: |
          set -e
          . .venv/bin/activate
          python main.py

      - name: Save XML (optional)
        if: ${{ env.SAVE_XML == 'true' || env.SAVE_XML == '1' }}
        uses: actions/upload-artifact@v4
        with:
          name: open-epg-xml
          path: |
            *.xml
            /tmp/open_epg_fetch_*.xml
          if-no-files-found: ignore
