name: LATAM Streams + GatoTV EPG

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 7 * * *" # daily 07:00 UTC

permissions:
  contents: read

concurrency:
  group: latam-epg
  cancel-in-progress: true

jobs:
  latam-streams-iptvcat:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    defaults:
      run:
        shell: bash
    env:
      IPTVCAT_START_URL: "https://iptvcat.com/latin_america__7/"
      IPTVCAT_MAX_PAGES: "0"            # 0 = crawl all pagination discovered
      PROBE_TIMEOUT_MS: "10000"
      PROBE_CONCURRENCY: "8"
      HEADLESS: "true"
      # DB
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
      SUPABASE_SCHEMA: "public"
      STREAMS_TABLE: "streams_latam"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm

      - name: Install deps
        run: |
          set -euo pipefail
          npm i --no-save playwright @supabase/supabase-js luxon
          npx playwright install --with-deps chromium

      - name: Run iptvcat crawler
        run: |
          set -euo pipefail
          node scripts/latam-iptvcat.mjs

      - name: Upload iptvcat artifacts
        uses: actions/upload-artifact@v4
        with:
          name: latam-streams
          path: |
            out/latam/pages.json
            out/latam/rows_raw.json
            out/latam/iptvcat_lists.json
            out/latam/iptvcat_probes.json
            out/latam/streams_latam.json
          if-no-files-found: warn

  gatotv-epg-24h:
    runs-on: ubuntu-latest
    timeout-minutes: 300
    needs: [latam-streams-iptvcat]
    defaults:
      run:
        shell: bash
    env:
      GATOTV_DIR_URL: "https://www.gatotv.com/canales_de_tv"
      GATOTV_TZ: "America/Mexico_City"
      PROGRAMS_HOURS_AHEAD: "24"
      GATOTV_MAX_CHANNELS: "0"          # 0 = all
      HEADLESS: "true"
      # DB
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
      SUPABASE_SCHEMA: "public"
      PROGRAMS_TABLE: "epg_programs"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm

      - name: Install deps
        run: |
          set -euo pipefail
          npm i --no-save playwright @supabase/supabase-js luxon cheerio
          npx playwright install --with-deps chromium

      - name: Run GatoTV EPG scraper (24h)
        run: |
          set -euo pipefail
          node scripts/mx-gatotv-all.mjs

      - name: Upload GatoTV artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gatotv-epg
          path: |
            out/mx/gatotv_directory.json
            out/mx/epg_programs_sample.json
          if-no-files-found: warn
