name: Sync live IPTV-org channels to Supabase (HTML search)

on:
  workflow_dispatch:
    inputs:
      countries:
        description: "Comma-separated ISO2 country codes (e.g. PR or PR,US)"
        required: false
        default: "PR,DE,US,ES,MX,IT,IE,CA,AU,UK"
  schedule:
    - cron: "0 */12 * * *"  # every 12 hours

jobs:
  sync:
    runs-on: ubuntu-latest
    concurrency:
      group: live-channels-sync
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Playwright (Chromium)
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          python -m playwright install --with-deps chromium

      - name: Run scraper (strict HTML playlist only)
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          COUNTRIES: ${{ inputs.countries }}
          SCRAPER_STRICT: "1"   # IMPORTANT: disable fallback to generic index.m3u
        run: |
          set -euo pipefail
          python scripts/sync_live_channels.py
