name: Sync live IPTV-org channels to Supabase

on:
  workflow_dispatch:
  schedule:
    - cron: "17 */6 * * *"   # every 6 hours

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run scraper
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: |
          python3 - <<'PY'
          import sys, runpy
          ns = runpy.run_path('.github/workflows/sync_live_channels.py')
          PY
